# Generated by Django 3.2.1 on 2021-08-12 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperQ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='question_group',
            field=models.ManyToManyField(related_name='person', to='paperQ.QuestionGroup'),
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='paperQ.questiongroup'),
        ),
    ]
