# Generated by Django 3.2.1 on 2021-08-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperQ', '0002_auto_20210812_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='question_group',
        ),
        migrations.AddField(
            model_name='person',
            name='question_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='paperQ.questiongroup'),
        ),
    ]
