# Generated by Django 3.2.1 on 2021-08-13 07:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paperQ', '0003_auto_20210812_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rest_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='person',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='answer_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
