# Generated by Django 3.2.1 on 2021-08-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperQ', '0004_auto_20210813_0721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['index']},
        ),
    ]
